[package]
name = "dianac"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary-int = "1.2.7"
bimap = "0.6.3"
bitbybit = "1.3.2"
clap = { version = "4.5.13", features = ["derive"] }
colored = "2.1.0"
strum = { version = "0.26.3", features = ["derive"] }
