name: tests

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "**" ]

env:
 CARGO_TERM_COLOR: always

jobs:
 app_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
